apiVersion: v1
kind: Namespace
metadata:
  name: 996ninja
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundval-deployment
  namespace: 996ninja
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fundval
  template:
    metadata:
      labels:
        app: fundval
    spec:
      containers:
        - name: fundval
          image: registry.cn-hongkong.aliyuncs.com/runnable-run/fundval:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 21345
          env:
            - name: OPENAI_API_KEY
              value: ""
            - name: OPENAI_API_BASE
              value: "https://api.openai.com/v1"
            - name: AI_MODEL_NAME
              value: "gpt-3.5-turbo"
          readinessProbe:
            httpGet:
              path: /health
              port: 21345
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 21345
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fundval-service
  namespace: 996ninja
spec:
  selector:
    app: fundval
  ports:
    - protocol: TCP
      port: 80
      targetPort: 21345
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fundval-ingress
  namespace: 996ninja
spec:
  rules:
    - host: demo-fundval.ddgod.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fundval-service
                port:
                  number: 80
    - host: demo-fundval.onetool.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fundval-service
                port:
                  number: 80
